### ISSUE TITLE
Proposal: Dynamic configurationName

### ISSUE THREAD

**Issue by DevShoesed** [micro-lc/element-composer#254]
## Problem
If I use micro-lc-element-composer alone, without micro-lc, the configurationName is fixed to 'microlc-element-composer'

## Proposal
I would like to use the url in the configurationName, so to decide on backend the right configuration for each request.

`
// example fe-container/src/index.tsx:55
const configurationName = window.location.pathname !== '/' ? window.location.pathname : 'microlc-element-composer'

`

**Comment by epessina** [comment]
Since version 2, composition functionalities are part of [micro-lc](https://github.com/micro-lc/micro-lc), and this issue has been solved.

Please, refer to the [official documentation](https://micro-lc.io) to know how micro-lc 2 works.
